# docker-compose.yml - Updated
version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: rag-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  api:
    build: .
    container_name: rag-api
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/rag_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - COLAB_EMBEDDING_URL=${COLAB_EMBEDDING_URL}
      - EMBED_DIM=384  # Đổi từ 768 về 384 cho model tiếng Việt
    ports:
      - "8000:8000"  # API chính
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  # Thêm embedding service riêng
  embedding:
    build: 
      context: .
      dockerfile: Dockerfile.embedding
    container_name: rag-embedding
    environment:
      - MODEL_ID=dangvantuan/vietnamese-document-embedding
      - TOKENIZERS_PARALLELISM=false
    ports:
      - "8001:8001"  # Embedding service
    restart: unless-stopped

volumes:
  postgres_data: